### ISSUE TITLE
when osis cannot connect need clean description

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#103]
Failed to connect to connections [['localhost', 5544, 1407390553.099565]]
Traceback (most recent call last):
~   File "mailrobot.py", line 17, in <module>
    j.servers.cloudrobot.startMailServer(robots=robots)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/lib/cloudrobots/CloudRobotFactory.py", line 30, in startMailServer
    self._init()
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/lib/cloudrobots/CloudRobotFactory.py", line 20, in _init
    self.osis =j.core.osis.getClientByInstance(osisinstance)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/grid/osis/OSISFactory.py", line 177, in getClientByInstance
    return self.getClient(ipaddr=ipaddr, port=port, user=user, passwd=passwd, ssl=ssl, gevent=gevent)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/grid/osis/OSISFactory.py", line 165, in getClient
    client= j.servers.geventws.getHAClient(connections, user=user, passwd=passwd,category="osis")
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/grid/geventws/GeventWSFactory.py", line 67, in getHAClient
    cl = DaemonClient(org=org, user=user, passwd=passwd, ssl=ssl, transport=trans,id=id)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/grid/serverbase/DaemonClient.py", line 80, in __init__
    self.transport.connect(self._id)
~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/grid/serverbase/TCPHATransport.py", line 53, in connect
    raise RuntimeError("Failed to connect to connections %s" % self._connections)
~ RuntimeError: Failed to connect to connections [['localhost', 5544, 1407390553.099565]]

type/level: UNKNOWN/critical
RuntimeError: Failed to connect to connections [['localhost', 5544, 1407390553.099565]]

DONT use raise error
use j.events.opscriticaerror...
make nice message this message is horrible

**Comment by despiegk** [comment]
opscritical error should only show right message not a backtrace
