### ISSUE TITLE
jsgrid disablenode does not work, tries to delete node from grid

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_core7#75]
(JSBOX)root@admin1:~# jsgrid disablenode -nid 10
sandbox:/opt/jsbox
ERROR
list indices must be integers, not str
Traceback (most recent call last):
~   File "/opt/jsbox/tools/jsgrid", line 279, in <module>
    _deleteNode(node)
~   File "/opt/jsbox/tools/jsgrid", line 179, in _deleteNode
    nid = node['id']
~ TypeError: list indices must be integers, not str

type/level: UNKNOWN/critical
TypeError: list indices must be integers, not str

**Comment by rkhamis** [comment]
remove cpu03 from york
